config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'sessions/index'
  get 'comment/edit'
  get 'cities/show'
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # gossips
  root to: 'gossips#index'
  # get '/gossips/:id', to: 'gossips#show', as: 'gossip' =>> fonctionne sans

  #resources
  resources :gossips
  resources :users
  resources :cities, only:[:show]
  resources :gossips do 
    resources :comments 
    resources :likes
  end

  resources :sessions

  # pages
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'
  get '/welcome/:name', to: 'pages#welcome'

  # users
  #get '/users/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/create_private_message.rb
class CreatePrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy
  has_many :likes
  
  validates :title,
  presence: true,
  length: { in: 3..14 }

  validates :content,
  presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage" 
  has_many :comments
  has_secure_password
  has_many :likes

  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include SessionsHelper

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def new
    @comment = Comment.create()
    @gossip = Gossip.find(params[:gossip_id])
  end
  
  def create
   @comment = Comment.new(user_id: current_user.id,
      content: params[:comment_content], gossip_id: params[:gossip_id])
    if @comment.save
      redirect_to gossip_path(params[:gossip_id])
    else 
      flash.now[:alert] = @comment.errors.full_messages
      render 'new'
    end
  end

  def update
    @comment = Comment.find(params[:id])
      if @comment.update(params_comment)
    redirect_to gossip_path(params[:gossip_id])
      else
      flash.now[:alert] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(params[:gossip_id])
  end

  private 
  def params_comment
    params.require(:comment).permit(:content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index, :create, :edit, :update, :destroy]
  include SessionsHelper

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all
  end

  def new
    @gossip = Gossip.create
  end

  def create
    @gossip = Gossip.new(user_id: current_user.id,
      'title' => params[:gossip_title],
      'content' => params[:gossip_content])
    if @gossip.save
      redirect_to gossips_path
      flash.now[:alert] = 'Yes congrats'
    else
      flash.now[:alert] = @gossip.errors.full_messages
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(params_gossip)
      redirect_to gossip_path(params[:id])
    else
      flash.now[:alert] = @gossip.errors.full_messages
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def params_gossip
    params.require(:gossip).permit(:content, :title)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Please log in.'
      redirect_to new_session_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include SessionsHelper

  def index
  end

  def new
    @like = Like.create
  end

  def create
    @like = Like.new(user_id: current_user.id, gossip_id: params[:gossip_id])
    if @like.save
    redirect_back(fallback_location: root_path)
    else
    render 'new'
    end
  end

  def show
  end

  def destroy
    @like = Like.find_by(gossip_id: params[:gossip_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def team; end

  def contact; end

  def welcome
    @name = params[:name]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  include SessionsHelper

  def new
  end
  
  def create
    user = User.find_by(email: params[:session_email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:session_password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.create()
  end
  
  def create
   @user = User.new(first_name: params[:user_name],
      email: params[:user_email],
      password: params[:user_password],
    city: City.all.sample)
    if @user.save
      redirect_to gossips_path
    else 
      flash.now[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<%# -------------------------------Content------------------------------- %>
<div class="container text-center">
  <!--   <h1>Voici la page du potin n°<%= params[:id]%></h1>-->
  <div class="row">
    <div class="col-sm-3 well">
      <%# -------------------------------Connected user------------------------------- %>
      <div class="well">
        <img src="https://source.unsplash.com/200x200/?city?sig=<%=rand(1..100)%>" 
                alt="city" class="rounded-circle img-fluid" style="width: 150px;">
<h3><strong>Ville : </strong></h3>
        <h4><%= @city.name %></h4>
      </div>
      <div>
        <%# -------------------------------Tags------------------------------- %>
        <%# <p><a href="#">Interests</a></p>
          <p>
            <span class="label label-default">News</span>
            <span class="label label-primary">W3Schools</span>
            <span class="label label-success">Labels</span>
            <span class="label label-info">Football</span>
            <span class="label label-warning">Gaming</span>
            <span class="label label-danger">Friends</span>
          </p> %>
        <%# -------------------------------End Tags------------------------------- %>
      
      </div>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <h2 class="text-center">Les Gossips de la ville</h2>
            </div>
          </div>
        </div>
        <% @city.gossips.each do |gossip| %>
          <div class="row d-flex justify-content-end">
            <div class="col-sm-9 d-flex">
              <div class="well m-5">
              <b><%= gossip.title %></b>
                <p><%= gossip.user.first_name %></p>
                <p class="text-decoration-none"><%= link_to 'Voir le gossip', gossip_path(gossip), class: "btn btn-info" %></p>
                <% if Like.find_by(gossip_id: gossip.id, user_id: current_user.id) %>
                  <% like = Like.find_by(gossip_id: gossip.id, user_id: current_user.id) %>
                  <%= button_to "#{gossip.likes.length } like(s)", gossip_like_path(gossip.id, like.id), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= form_tag gossip_likes_path(gossip.id), method: "post" do %>
                    <%= submit_tag "#{gossip.likes.length } Like(s)", class:"btn btn-default btn-sm" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= form_for [@gossip, @comment] do |f|%>
  <div class='form-group'>
    <label> Content </label>
    <%= f.text_area :content, class: 'form-control' %>
</div>
  <div class='form-group'>
   <%= submit_tag "Editer le commentaire" %>  </div>
<% end %>
  <%= button_to 'Supprimer le commentaire', gossip_comment_path(@gossip.id, @comment.id), method: :delete, class: "btn btn-danger"%>

app/views/comments/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'comment_content', @comment.content %>
      <br />
      <br />
      <%= submit_tag "Créer un commentaire" %>
    <% end %>

app/views/gossips/edit.html.erb
<%= form_for @gossip do |f|%>
  <div class='form-group'>
    <label> Titre </label>
    <%= f.text_field :title, class: 'form-control' %>
</div>
  <div class='form-group'>
    <label> Content </label>
    <%= f.text_area :content, class: 'form-control' %>
</div>
  <div class='form-group'>
   <%= submit_tag "Edit Gossip" %>  </div>
<% end %>

app/views/gossips/index.html.erb
<div class="container marketing">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default text-left">
        <div class="panel-body">
          <h1 class="text-center text-info">Les Gossips</h1>
          <p class="text-decoration-none"><%= link_to 'Créer un Gossip', new_gossip_path(), class: "btn btn-info" %></p>
        </div>
      </div>
    </div>
    <div class="row ml-5">
      <% @gossips.each do |gossip| %>
        <div class="col-lg-3 well m-3">
          <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..100)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
          <h3><%= gossip.user.first_name %></h2>
          <h4><%= gossip.title %></h4>
          <p>Nombre de commentaire(s) : <%= gossip.comments.length %></p>
          <div class="row ml-3 pt-4">
            <% if Like.find_by(gossip_id: gossip.id, user_id: current_user.id) %>
              <% like = Like.find_by(gossip_id: gossip.id, user_id: current_user.id) %>
              <%= button_to "#{gossip.likes.length } like(s)", gossip_like_path(gossip.id, like.id), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= form_tag gossip_likes_path(gossip.id), method: "post" do %>
                <%= submit_tag "#{gossip.likes.length } Like(s)", class:"btn btn-default btn-sm" %>
              <% end %>
            <% end %>
            <div class="col">
              <p class="text-decoration-none"><%= link_to 'Voir le gossip', gossip_path(gossip), class: "btn btn-info" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/gossips/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <%= label_tag 'Title' %>
      <%= text_field_tag 'gossip_title', @gossip.title %>
      <br />
      <br />
      <%= label_tag 'Content' %>
      <%= text_area_tag 'gossip_content', @gossip.content %>
      <br />
      <br />
      <%= submit_tag "Create Gossip" %>
    <% end %>

app/views/gossips/show.html.erb
<%# -------------------------------Content------------------------------- %>
<div class="container text-center">
  <!--   <h1>Voici la page du potin n°<%= params[:id]%></h1>-->
  <div class="row">
    <div class="col-sm-3 well">
      <%# -------------------------------Connected user------------------------------- %>
      <div class="well">
        <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..100)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
        <h3><strong><%= @gossip.user.first_name %> <%= @gossip.user.last_name %></strong></h3>
        <p class="text-decoration-none"><%= link_to "Page Auteur", user_path(@gossip.user), class: "btn btn-info" %></p>
      </div>
      <div class="well">
        <%# -------------------------------Tags------------------------------- %>
        <%# <p><a href="#">Interests</a></p>
          <p>
            <span class="label label-default">News</span>
            <span class="label label-primary">W3Schools</span>
            <span class="label label-success">Labels</span>
            <span class="label label-info">Football</span>
            <span class="label label-warning">Gaming</span>
            <span class="label label-danger">Friends</span>
          </p> %>
        <%# -------------------------------End Tags------------------------------- %>
        <h3><strong>Ville : </strong></h3>
        <h4><%= @gossip.user.city.name %></h4>
        <p class="text-decoration-none"><%= link_to "Page Ville", city_path(@gossip.user.city), class: "btn btn-info" %></p>
      </div>
      <div >
      </div>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <h2 class="text-center"><%= @gossip.title %></h2>
              <p> Le gossip : <%= @gossip.content %></p>
              <div class="lign"> <hr> </div>
              <div class="row ">
                <div class="col-sm">
                  <p class="text-decoration-none"><%= link_to "Créer un commentaire", new_gossip_comment_path(@gossip.id), class: "btn btn-secondary" %></p>
                </div>
                <div class="col-sm">
                  <% if Like.find_by(gossip_id: @gossip.id, user_id: current_user.id) %>
                    <% like = Like.find_by(gossip_id: @gossip.id, user_id: current_user.id) %>
                    <%= button_to "#{@gossip.likes.length } like(s)", gossip_like_path(@gossip.id, like.id), method: :delete, class: "btn btn-danger" %>
                  <% else %>
                    <%= form_tag gossip_likes_path(@gossip.id), method: "post" do %>
                      <%= submit_tag "#{@gossip.likes.length } Like(s)", class:"btn btn-default btn-sm" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="lign"> <hr> </div>
              <div class="row d-flex justify-content-between">
                <% if current_user == @gossip.user %>
                  <div class="col-sm ">
                    <p class="text-decoration-none"><%= link_to "Editer le gossip", edit_gossip_path(@gossip), class: "btn btn-primary" %></p>
                  </div>
                  <div class="col-sm">
                    <%= button_to 'Supprimer le potin', gossip_path(@gossip), method: :delete, class: "btn btn-danger"%>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% @comments.each do |comment| %>
        <% if comment.gossip_id == @gossip.id %>
          <div class="row">
            <div class="col-sm-3">
              <div class="well">
                <b><%= comment.user.first_name %> <%= comment.user.last_name %></b>
                <%# <img src="bird.jpg" class="img-circle" height="55" width="55" alt="Avatar"> %>
              </div>
            </div>
            <div class="col-sm-9">
              <div class="well">
                <p><%= comment.content %>
                  <%# A tester V-1 %>
                  <% if current_user == comment.user %>
                    <p class="text-decoration-none"><%= link_to "Editer le commentaire", edit_gossip_comment_path(@gossip.id, comment.id), class: "btn btn-primary" %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container-fluid well">
<%= form_tag url_for(action: 'create'), method: "post",  class:"mb-3" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="mb-3">
    <%= label_tag 'Prénom' %>
    <%= text_field_tag 'user_name', @user.first_name, placeholder:"John" %>
  </div>
  <div class="mb-3">
    <%= label_tag 'Nom' %>
    <%= text_field_tag 'user_last_name', @user.last_name, placeholder:"Doe" %>
  </div>
  <div class="mb-3">
    <%= label_tag 'Age' %>
    <%= text_field_tag 'user_age', @user.age, placeholder:"18" %>
  </div>
  <div class="mb-3">
    <%= label_tag 'Biographie' %>
    <%= text_field_tag 'user_description', @user.description, placeholder:"..." %>
  </div>
  <div class="mb-3">
    <%= label_tag 'E-mail' %>
    <%= email_field_tag 'user_email', @user.email, placeholder:"email@exemple.com" %>
  </div>
  <div class="mb-3">
    <%= label_tag 'Mot de passe' %>
    <%= password_field_tag 'user_password', @user.password, placeholder:"Mot de passe" %>
  </div>
  <%= submit_tag "Créer mon compte", class:"btn btn-info mb-5"  %>
<% end %>
</div>

app/views/users/show.html.erb
<%# -------------------------------Content------------------------------- %>
<div class="container text-center">
  <div class="row">
    <div class="col-sm-3 well">
      <%# -------------------------------Connected user------------------------------- %>
      <div class="well">
        <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
        <h3><strong> User : </strong></h3>
        <h4><%= @user.first_name %> <%= @user.last_name %></h4>
      </div>
      <div>
        <%# -------------------------------Tags------------------------------- %>
        <%# <p><a href="#">Interests</a></p>
          <p>
            <span class="label label-default">News</span>
            <span class="label label-primary">W3Schools</span>
            <span class="label label-success">Labels</span>
            <span class="label label-info">Football</span>
            <span class="label label-warning">Gaming</span>
            <span class="label label-danger">Friends</span>
          </p> %>
        <%# -------------------------------End Tags------------------------------- %>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <h2 class="text-center">Plus d'informations sur cet utilisateur</h2>
              <h3>Age : <%= @user.age %></h3>
              <h3>Description : <%= @user.description %></h3>
                <h3><span class="fas fa-envelope-open"></span><%= @user.email %></h3>
              <h3>Ville : <%= @user.city.name %></h3>
            
              <p class="text-decoration-none"><%= link_to 'Voir la page de cette ville', city_path(@user.city), class: "btn btn-info" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>