config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'sessions/index'
  get 'comment/edit'
  get 'cities/show'
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # gossips
  root to: 'gossips#index'
  # get '/gossips/:id', to: 'gossips#show', as: 'gossip' =>> fonctionne sans

  #resources
  resources :gossips
  resources :users
  resources :cities, only:[:show]
  resources :gossips do 
    resources :comments 
    resources :likes
  end

  resources :sessions

  # pages
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'
  get '/welcome/:name', to: 'pages#welcome'

  # users
  #get '/users/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/create_private_message.rb
class CreatePrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy
  has_many :likes
  
  validates :title,
  presence: true,
  length: { in: 3..14 }

  validates :content,
  presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage" 
  has_many :comments
  has_secure_password
  has_many :likes

  validates :password, presence: true, length: { minimum: 6 }
  validates :email, presence: true
  validates :first_name, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index, :create, :edit, :update, :destroy]
  include SessionsHelper

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.all
  end

  def new
    @gossip = Gossip.create
  end

  def create
    @gossip = Gossip.new(user_id: current_user.id,
      'title' => params[:gossip_title],
      'content' => params[:gossip_content])
    if @gossip.save
      redirect_to gossips_path
      flash.now[:alert] = 'Yes congrats'
    else
      flash.now[:alert] = @gossip.errors.full_messages
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(params_gossip)
      redirect_to gossip_path(params[:id])
    else
      flash.now[:alert] = @gossip.errors.full_messages
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def params_gossip
    params.require(:gossip).permit(:content, :title)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = 'Please log in.'
      redirect_to new_session_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include SessionsHelper

  def index
  end

  def new
    @like = Like.create
  end

  def create
    @like = Like.new(user_id: current_user.id, gossip_id: params[:gossip_id])
    if @like.save
    redirect_back(fallback_location: root_path)
    else
    render 'new'
    end
  end

  def show
  end

  def destroy
    @like = Like.find_by(gossip_id: params[:gossip_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def team; end

  def contact; end

  def welcome
    @name = params[:name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.create()
  end
  
  def create
   @user = User.new(first_name: params[:user_name],
      email: params[:user_email],
      password: params[:user_password],
    city: City.all.sample)
    if @user.save
      redirect_to gossips_path
    else 
      flash.now[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <link href="https://e7.pngegg.com/pngimages/301/863/png-clipart-computer-icons-icon-design-user-favicon-audience-room-desktop-wallpaper.png" rel="icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap CSS %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%# Bootstrap CSS Suppl %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <%# Bootstrap JS %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%# Fontawesome JS %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css%22%3E 
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css ">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <strong><%= link_to "The Gossip Project", root_path, class: "navbar-brand" %></strong>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "A propos", team_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Nous contacter", contact_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item active">
              <div class="dropdown">
                <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user"></i> Mon compte
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% if current_user %>
                    <%= button_to 'Se déconnecter', session_path(session.id), method: :delete, class: "btn btn-link"%>
                  <% else %>
                    <%= link_to "Connexion", new_session_path, class: "nav-link" %>
                    <%= link_to "Inscription", new_user_path, class: "nav-link" %>
                  <% end %>
                </div>
              </div>
            </li>
            <!--    <li>
              <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </li>-->
          </ul>
        </div>
      </nav>
    </header>
    
    <div class="container-fluid p-10">
      <% flash.each do |type, msg| %>
        <% case msg %>
        <% when "Yes congrats"%>
        <div class="alert alert-info">
          <%= msg %>
        </div>
        <% when "Invalid email/password combination"%>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
        <% when "Please log in."%>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
      <% else %>
        <% if msg.kind_of?(Array) %>
          <% msg.each do |bla| %>
            <div class="alert alert-danger">
              <%= bla %></br>
          </div>
        <% end %>
      <% end %>
    <% end %>
  
  <% end %>
  <%= yield %>

  <footer class=" footer d-flex flex-wrap align-items-center py-3 my-4 border-top fixed-bottom">
    <span class="text-muted">&copy; 2022 The Gossip Project, Inc</span>
  </footer>
</body>
</html>

app/views/pages/contact.html.erb
  <h1 class="text-center text-info">Nous contacter</h1>
  <br>
  <br>
  <br>
  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Adresse e-mail</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="nom@exemple.com">
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Nous contacter</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
  <br>
  <br>
  <br>
  <br>
  <h3 class="fs-3">The Gossip Project</h3>
  <p class="fw-normal">1989 branche des étoiles,<br>
    12ème arbre de la forêt,<br>
    38520 Pathiboulin<br>
    <span class="fas fa-phone"></span> 09 87 78 65 44<br>
    <span class="fas fa-envelope-open"></span> the-gossip-project@protonmail.com
  </p>

app/views/pages/home.html.erb
    <h1>Mon super site de gossip, depuis le dossier views !</h1>

app/views/pages/team.html.erb
  
<div class="container marketing">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default text-left">
        <div class="panel-body">
          <h1 class="text-center text-info"> Notre équipe</h1>
<h2 class="text-center">Constitué de deux moussaillons armés de patience et de :as (:lol: AKA privatejoke)</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default text-left">
        <div class="panel-body">
<p>Le premier Moussaillon est Matthias :<br>
   * Son prénom contient un H<br>
  * Le premier gossip est lié à lui. L'histoire raconte qu'il a mangé le chat d'Iris... Et étonnamment ils s'entendent bien malgré ça !</p>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-default text-left">
        <div class="panel-body">
<p>Le second Moussaillon est Iris :<br>
   * Elle raconte des gossips faux<br>
  * Et étonnament tout le monde s'en doute </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<p> welcome <%= @name %> </p> 